### ISSUE TITLE
Improve free-format expression parsing

### ISSUE THREAD

**Issue by DavidGregory084** [rpgleparser/rpgleparser#1]
The associativity and priority of operators is sometimes wrong.

I need to integrate some ideas from [DavidGregory084/grammar-rpg-antlr4](https://github.com/DavidGregory084/grammar-rpg-antlr4).

**Comment by ryaneberly** [comment]
Finally took a few minutes to read your code a bit more thoroughly.
I think we should bring in your reserved words stuff as well.

**Comment by UdayaBhanuG** [comment]
Currently for multiline if condition, it throws error saying the following: please improve it. 

line 377:108 no viable alternative at input 'retst=4or\r\n'

**Comment by TheEricWilson** [comment]
Would you provide a junit that makes the failure evident? You can copy/paste the code as a reply and when we are able to we will incorporate it and address the issue. We are very early in development so breaking changes will likely happen often.

Thanks
Eric

**Comment by ryaneberly** [comment]
Even just the couple lines of code around that problem would help.

**Comment by UdayaBhanuG** [comment]
This is the expression that fails. 

     c                   if        retst = 4   or                                                           
     c                             retst = 2                                                                
     c                   eval      retst = 1                                                                
     c                   endif                                                                              

I guess in RpgParser.g4, we do not look for multi-line expressions in this way. I guess that leads to this kind of problems.

**Comment by UdayaBhanuG** [comment]
This is the expression that fails. 

     c                   if        retst = 4   or                                                           
     c                             retst = 2                                                                
     c                   eval      retst = 1                                                                
     c                   endif                                                                              

I guess in RpgParser.g4, we do not look for multi-line expressions in this way. I guess that leads to this kind of problems.

**Comment by UdayaBhanuG** [comment]
This is the expression that fails. 

     c                   if        retst = 4   or                                                           
     c                             retst = 2                                                                
     c                   eval      retst = 1                                                                
     c                   endif                                                                              

I guess in RpgParser.g4, we do not look for multi-line expressions in this way. I guess that leads to this kind of problems.

**Comment by UdayaBhanuG** [comment]
This is the expression that fails. 

     c                   if        retst = 4   or                                                           
     c                             retst = 2                                                                
     c                   eval      retst = 1                                                                
     c                   endif                                                                              

I guess in RpgParser.g4, we do not look for multi-line expressions in this way. I guess that leads to this kind of problems.

**Comment by UdayaBhanuG** [comment]
This is the expression that fails. 

     c                   if        retst = 4   or                                                           
     c                             retst = 2                                                                
     c                   eval      retst = 1                                                                
     c                   endif                                                                              

I guess in RpgParser.g4, we do not look for multi-line expressions in this way. I guess that leads to this kind of problems.

**Comment by UdayaBhanuG** [comment]
This is the expression that fails. 

     c                   if        retst = 4   or                                                           
     c                             retst = 2                                                                
     c                   eval      retst = 1                                                                
     c                   endif                                                                              

I guess in RpgParser.g4, we do not look for multi-line expressions in this way. I guess that leads to this kind of problems.

**Comment by UdayaBhanuG** [comment]
This is the expression that fails. 

     c                   if        retst = 4   or                                                           
     c                             retst = 2                                                                
     c                   eval      retst = 1                                                                
     c                   endif                                                                              

I guess in RpgParser.g4, we do not look for multi-line expressions in this way. I guess that leads to this kind of problems.

**Comment by UdayaBhanuG** [comment]
This is the expression that fails. 

     c                   if        retst = 4   or                                                           
     c                             retst = 2                                                                
     c                   eval      retst = 1                                                                
     c                   endif                                                                              

I guess in RpgParser.g4, we do not look for multi-line expressions in this way. I guess that leads to this kind of problems.

**Comment by TheEricWilson** [comment]
UdayaBhanuG I think I know what your problem is... The text that you are feeding it is not padded out past the comment section, Right now we are paying attention to the position of the newline characters and they must be past the comment area.

Our jUnits have a scenario like this.
    @Test
    public void testCSpec_EVAL_continuation() {
        String inputString =
                "     C                   eval      DATA = 'Current Policy Term:  ' +\r\n" +
                        "     C                                    %trim(EffDateChr) + ' to ' +\r\n" +
                        "     C                                    %trim(ExpDateChr)\r\n";

        expectTokensForSourceLines(inputString, "C", "", "", "", "", "eval", "DATA", "=", "'",
                "Current Policy Term:", "'", "+", "%trim", "(", "EffDateChr",
                ")", "+", "'", "to", "'", "+", "%trim", "(", "ExpDateChr", ")",
                "");
    }
The expectTokensForSourceLines method expands the input lines to be the right size so things work correctly. When reading directly from a source member this is not a problem since the new lines occur in the right places, it is just when you take code and enter it from scratch or use the iSeries RPG source code editor and download a member to your PC that this problem manifests itself (I hit that too).

It is possible that we will rework that portion of the grammar to ignore the newlines etc...

**Comment by ryaneberly** [comment]
I see the problem.  
from the ILE RPG Reference:
Extended factor 2:
"may optionally span multiple lines. If specified across multiple
lines, the continuation lines must be blank in positions 7-35."

I don't think the parser is handling this yet.

**Comment by ryaneberly** [comment]
UdayaBhanuG , your issue is fixed.

**Comment by ryaneberly** [comment]
David, 
  I grabbed your order of operations logic.  Works much better.  Thanks.

Can you explain the &lt;assoc=right&gt; part of the line.
&lt;assoc=right&gt; expression EXP expression

After googling, I'm still not getting it.

**Comment by DavidGregory084** [comment]
Hi Ryan,
 The assoc keyword changes the associativity of an operator. the default is left associativity, i.e.

`-` is left associative, so

```scala
1 - 2 - 3 - 4 = (((1 - 2) - 3) - 4)
```

however, `**` is right-associative, so:

```scala
1 ** 2 ** 3 ** 4 = (1 ** (2 ** (3 ** 4)))
```

It means that expressions which use `**` will be parsed correctly without using parentheses to clarify associativity.

Hopefully that makes sense: for operators like `-` where the order in which they are applied matters ("non-commutative", in other words), the associativity can affect the result of an expression and therefore how it is parsed.

**Comment by DavidGregory084** [comment]
P.S. I ought to clarify that the order I've used is from the Expressions section of the ILE RPG Reference so I think it should be right: http://publib.boulder.ibm.com/iseries/v5r2/ic2924/books/c092508428.htm

**Comment by TheEricWilson** [comment]
Here is the latest version that I know of

http://www-01.ibm.com/support/knowledgecenter/#!/ssw_ibm_i_71/books/sc092508a.pdf

**Comment by ryaneberly** [comment]
Of course.  I follow now.  Thanks, David.

**Comment by ryaneberly** [comment]
implemented.
