### ISSUE TITLE
I am going to create an examples package and put my code in there

### ISSUE THREAD

**Issue by TheEricWilson** [rpgleparser/rpgleparser#10]
It is a work in progress, with a few hundred TODO in it but I figure now is as good of time as any.

**Comment by ryaneberly** [comment]
Nice.  very intrigued.   Would it be useful to have the operations each have there own tree event?

in addition to 
exitCspec_fixed(..) 

you'd have
exitOpWRITE()
or something of that nature?

**Comment by TheEricWilson** [comment]
Yeah having things parsed out fully would rock. Right now the work you see is something I am doing for work. So big changes might make me cry :-)

**Comment by ryaneberly** [comment]
I gotcha. I'm picturing *adding* it in this case.  It would be backwards
compatible with your code methinks.

**Comment by TheEricWilson** [comment]
Sounds great!

**Comment by danielgoodwin** [comment]
I have ILE and JAVA experience, little ANTLR.

I'd like to extend (or copy and change) the existing fixed2free example and in fact work the other way for legacy reasons (ie free2fixed). 

I've been reading through grammar, am I right in saying there is no support for parsing of BIF (Built in functions) yet eg %ADDR / %ABS etc. If not I might have a go at it as well. I would need the specific BIF operations for translation.

**Comment by ryaneberly** [comment]
Welcome Daniel.

We expanded the fixed operations because they all have their own 'format'.  Admittedly some are similar and could have been grouped together.  I'm inclined to treat BIFs the same way we handle all function/subprocedure and external programs calls.   

Something like this would match all the BIF calls.

        @Override
        	public void enterFunction(FunctionContext ctx) {
        		if(ctx.functionName().getText().startsWith("%")){
        			System.out.println("BIF - " + ctx.functionName().getText());
        			//Add code here..
        		}
        		super.enterFunction(ctx);
        	}


Thoughts?

**Comment by TheEricWilson** [comment]
It might be better to parse them fully for correctness purposes at least in the number of arguments given

**Comment by ryaneberly** [comment]
I'm ok with that.  daniel, if you are interested, contribs are welcome

**Comment by TheEricWilson** [comment]
I am still working on the fixed 2 free stuff. I think it would be cool if you created the free 2 fixed though.

**Comment by danielgoodwin** [comment]
Im working on the changes for BIFs and then onward to the free2fixed. I intend to parse the BIFs completely as I will need specific code back routines for free2fixed. 
Will be a background work as not my day job, I'll probably do interim release when I have BIFs done and unit tests for those.

**Comment by ryaneberly** [comment]
Sounds good.
FYI.  The BIFs listed here:
http://publib.boulder.ibm.com/iseries/v5r2/ic2924/books/c092508302.htm#ToC_706
have code samples you could leverage.

**Comment by TheEricWilson** [comment]
Ok so in my quest to make this fixed to free stuff work I am going to have to make a symbol table and likely do the /COPY and External file stuff in the process. That means I will also need to work on the conditional compile stuff too (IF DEFINED etc)

I am thinking that I would implement those as other listeners (because the existing one is too big as it is. They also could be used in isolation anyway.

What do you guys think. (I am going to post my code in the early stages so you can see how I am tackling it)

**Comment by ryaneberly** [comment]
@TheEricWilson , I think we can close this "issue".  The project is spun off on it's own in examples.  We can create new conversations as needed.

**Comment by TheEricWilson** [comment]
Sounds good!
