### ISSUE TITLE
Add C operation codes to the parse tree

### ISSUE THREAD

**Issue by ryaneberly** [rpgleparser/rpgleparser#11]
in addition to 
 exitCspec_fixed(..)
 
add
 exitOpWRITE()

**Comment by TheEricWilson** [comment]
Thanks Ryan!

**Comment by ryaneberly** [comment]
take a look.  I added ACQ - CALLB.

**Comment by TheEricWilson** [comment]
I will Monday? I am not near my computer

**Comment by ryaneberly** [comment]
LOL.  Of course.  Have a great weekend.

**Comment by TheEricWilson** [comment]
Looks good Ryan, things did not explode while testing either :-) Do you want to fill in the rest? I am sorry that I am such a noob when it comes to ANTLR. I could follow your example if you like but I still find it easier for one person to edit a given source file...

I will go ahead and try to refactor the example to use the new features of the parser. 

Another thing I have been thinking about is how to handle the multi-line things like KLISTs etc... I think they should be handled like statement blocks in C but I have no idea how to make that happen.

Thanks
Eric

**Comment by TheEricWilson** [comment]
Ryan, I added the opcodes that were remaining (actually all the opcodes and commented out the redefinition ones... I will leave the RpgParser stuff for you since you seem to have a better handle on that sort of thing. Hopefully having the lexer symbols will make your life a little better

**Comment by TheEricWilson** [comment]
On second thought. I am going ahead and trying to flesh out the RpgParser.g4 too by following your example

**Comment by TheEricWilson** [comment]
I think I got it all done as far as parsing and lexing goes. The fixed2free is in the process of being refactored... I will get that working tomorrow (i hope)

**Comment by ryaneberly** [comment]
Great. I'll take a look when I get a chance.

**Comment by ryaneberly** [comment]
Looks good.  

the extended C spec (free form) is converted also.  closing
