### ISSUE TITLE
Issue found with the handling of END opcode

### ISSUE THREAD

**Issue by TheEricWilson** [rpgleparser/rpgleparser#13]
It looks like the changes in the lexer and parser to support nesting has caused the following issue.
Given an opcode of END it appears the lexer is not handling it.

line 375:31 no viable alternative at input 'C                   END\r\n'
line 375:31 no viable alternative at input '\r\n'

The lines in question look like
   C                   IF        theDogIsHungry or theDogIsDead  
   C                   END

**Comment by ryaneberly** [comment]
I think this is working.  fixed as part of #14.  
see 
resources\org\rpgleparser\tests\nesting\block\if\if.end.rpgle

**Comment by ryaneberly** [comment]
Eric, can you confirm that the problem you saw is resolved?
