### ISSUE TITLE
Tokens being merged???

### ISSUE THREAD

**Issue by TheEricWilson** [rpgleparser/rpgleparser#14]
select;
          when inTrigBuff.triggerEvent = '1';
             event = 'Insert';
             outUserXML += '<Event>Insert</Event>';
          when inTrigBuff.triggerEvent = '2';
             event = 'Delete';
             outUserXML += '<Event>Delete</Event>';
          when inTrigBuff.triggerEvent = '3';
             event = 'Update';
             outUserXML += '<Event>Update</Event>';
          when inTrigBuff.triggerEvent = '4';
             event = 'Read';
             outUserXML += '<Event>Read</Event>';
          other;
             event = 'Unknown';
             outUserXML += '<Event>Unknown</Event>';
       endsl;

I am getting the following error 

line 291:15 no viable alternative at input 'wheninTrigBuff' 

which looks like the tokens are being merged (or something)

**Comment by ryaneberly** [comment]
fixed.  Thanks Eric.
