### ISSUE TITLE
/free parsing issues

### ISSUE THREAD

**Issue by danielgoodwin** [rpgleparser/rpgleparser#17]
Ryan
Wonder if you could get chance to look at following
I'm just starting some /free code parsing and hitting problems with
- truncated lines (if not padded) - code was originally ftp'ed so not padded out
- comments on line on their own // format
- as Im starting with first opcodes, so ACQ 
- error when I use an extender eg ACQ(e) grammar does not seem to allow for brackets.
(commented out below which is when I have problem with comments I think);

(apologies if following code sample is wrong syntactically)

     C     *Entry        PList
     C                   Parm                    w_RtnValue

      /Free

          ExSr ProgInit;
          
          acq qpadev0 ORCH01DSPF;
		  //ACQ(e) qpadev1 ORCH01DSPF;

      /end-free

**Comment by ryaneberly** [comment]
For the line truncation use:
ANTLRInputStream input = new ANTLRInputStream(new FixedWidthBufferedReader(inputString));
or
ANTLRInputStream input = new ANTLRInputStream(new FixedWidthInputStream(inputStream));

**Comment by ryaneberly** [comment]
You raised an issue that the free form extenders weren't working correctly.  Pull master into your branch, and it should improve.

**Comment by danielgoodwin** [comment]
Pulling latest code, Having problem compiling it with lexer line (line 1105)
FreeOpExtender_Any: -> popMode,skip;

**Comment by TheEricWilson** [comment]
Compile with ANTLR 4.5 any lower causes an error

**Comment by ryaneberly** [comment]
Hmm.  That bit is a bit of a hack.  Operation extenders are a bit odd,
difficult to distinguish from call statements parsing wise.  I didn't know
it would cause any compatibility issues.  Let me know if you can't resolve
it.

**Comment by danielgoodwin** [comment]
Thanks . thats it
