### ISSUE TITLE
Opcode Validation

### ISSUE THREAD

**Issue by danielgoodwin** [rpgleparser/rpgleparser#19]
Im adding in some Opcode validation files.
Couple of  these have parsing  issues on the fixed side.
Example are 'more or less' taken from 7.1 ILE reference manual.

ADDDUR.rpgle
`
     C     T'00:00 am'   adddur    12:*Hours     result 
`
Timeliteral seems to be problem, but I cant figure it out.

CALLP.rpgle
` 
    C                   CALLP(e)  proc2(parm1:parm2)
`
`
     C                   CALLP(e)  proc3(arr(x) + 1)
`
For Callp it seems to be the extender. I cant be sure if its only because its in an extended factor 2 or not.

**Comment by danielgoodwin** [comment]
Few more..
DOU 
```
     C                   DOU       *IN01 
     C                   ENDDO   
     C                   DOU       *IN01 = *OFF
     C                   ENDDO 
     C                   DOU(m)    *IN01 = *OFF
     C                   ENDDO  
     C                   dou       *IN01 = *OFF or (fld2>fld3)
     C                   end
```
DOW
```
    C                   DOW(m)    *IN01 = *OFF
```

**Comment by TheEricWilson** [comment]
Looks like it is all Extended Factor 2 syntax, I have not been looking too much at that as most everything I have source wise here is fixed format (some dating back to the late 1980s (Sys/38 RPG even)

**Comment by ryaneberly** [comment]
fixed the extender lexing.   The time literal needs to be lexed differently.  Know of any more examples of literals in factor1?

**Comment by TheEricWilson** [comment]
*JOBRUN would be one

**Comment by danielgoodwin** [comment]
Other than the normal quoted literals ..

- Graphic literals G'..'
- Date literals D'xx-xx-xx'
- Timestamp literals Z'.' Dont think they fit in Factor 1
- UCS literals U'xxx' for DBCS


Other opcodes eg DEFINE
- symbolics - probably already handled eg *LIKE/*DTAARA


```
C     G'oBBi'       SCAN      Graffld:2     Number            5 0    90
C     *LIKE         DEFINE    FLDA          FLDP
C     *DTAARA       DEFINE    TOTAL         TOTNET
```

**Comment by TheEricWilson** [comment]
In the date, time, timestamp fields do not forget that the separator can be things other than dashes or dots or colons too

**Comment by ryaneberly** [comment]
It's implemented.  Though not to the degree of separating out hours/minutes/seconds.  I think we'll leave that to the consumer.  Everything inside the quotes is a single lexical unit (except for escaped quotes - do they apply here?)

**Comment by TheEricWilson** [comment]
When one uses a figurative constant the different separator can be added *YMD- for example

**Comment by danielgoodwin** [comment]
Thanks for the help so far.
Ive now created tests for all the opcodes both fixed (and free where appropriate) 
Any that are passing, I've committed.
I'm going to try to resolve some of the failing ones, but with being an ANTLR novice I may ask for help if I can't progress.

**Comment by ryaneberly** [comment]
Thanks for doing that.  Knowing what's broken is half the work.

**Comment by danielgoodwin** [comment]
Got a few done.. 
Now a few I'm stuck on, suggestions welcome

Fixed spec FOR, tried sort of copying IF/ENDIF but still stuck
```
      *
     C                   FOR       X = 1 to 10 
     C                   ENDFOR   
     C                   For       X1 = 1 by 1 to 10
     C                   endfor
     C                   For       X1= 10 downto 1
     C                   Endfor
     C                   FOR       X= 10 by 1 downto 1
     C                   endfor
     C                   for       X1= %len(str) by 1 downto 1
     C                   endfor
 ```

PARM, when using a factor1 entry - something to do with CS_BlankFactor I guess..
```
C     *IN30         PARM      *IN27         BYTE
```

Return with an operation extender both fixed and free, I can see modifier as optional in grammar..
```
     C                   RETURN(H) MYVAR + 10
      /Free
          return(h) (myvar + 10);
      /end-free
```

Couple of EVAL using arrays/dot construction
```
arr(*) = field2 * filed3;
cust(custom).account(accum).balance -= 24;

```

SELECT/WHEN
```
          select;
          when not(*in01) and (fld = 'xx');
          when %sst(a:(x+4):3) = 'ABC';
          when(m) ((Y > 2) and (X<5));
          other;
          end;
```

I have just a few more, but trying to solve them myself.

**Comment by ryaneberly** [comment]
Nice work.  You found some interesting cases.

I'll take a look later tonight.

**Comment by ryaneberly** [comment]
I fixed FOR,PARM,and RETURN

select has me perplexed.  It's taking the branch that treats 'select' as an indentifier,not an op.

The eval on arr(*) creates a MULT_NOSPACE token.  That token should be eliminated, I think.  That was an attempt to distinguish multiply from *ALL

**Comment by danielgoodwin** [comment]
Just on the RETURN opcode
The example I had was part of a bigger one (below)
The default Fixed spec RETURN without parameters is now not parsing. (first one below). 
```
     C                   RETURN
     C                   RETURN    MYDS
     C                   RETURN    MYVAR + 10
     C                   Return    D'1995-10-01'
     C                   RETURN(H) MYVAR + 10
      /Free
          return;
          return myds;
          return (myvar + 10);
          return D'1995-10-01';
          return(h) (myvar + 10);
      /end-free
```

**Comment by ryaneberly** [comment]
@danielgoodwin, 
   I don't think "end" is a valid keyword in Free.  It should be *endsl*,    "end" does not compile for me in v7r1.

  However, it is still treating "other" as a statement within the last when clause.  I need to figure that out.

**Comment by ryaneberly** [comment]
i think the issues around this are resolved.
