### ISSUE TITLE
// Comments after code

### ISSUE THREAD

**Issue by danielgoodwin** [rpgleparser/rpgleparser#23]
Having an issue where // comments follow code..
Think problem is free_linecomments which I think is expecting // comment to take all of line.
I have added test case to /tests/comments/slashslashaftercode.rpgle.fail

Example
```
      /FREE
             If Pos > 0; // Now try to find the end
                Pos2 = %Scan('%>':MsgLine:Pos+2);
             endif;
      /END-FREE 

```

**Comment by ryaneberly** [comment]
Thanks Daniel,
   I'll look into it

**Comment by danielgoodwin** [comment]
Ryan
Ive changed following in Lexer which 'seems' to fix it but I would like you to look at it before commiting
There may be use cases for what I think you are trying to do

```
mode FIXED_CommentMode_HIDDEN;
COMMENTS_TEXT_SKIP : [ ]+ -> skip;
//COMMENTS_TEXT_HIDDEN : ~[ ] ~[\r\n]+ -> channel(HIDDEN);
COMMENTS_TEXT_HIDDEN :  ~[\r\n]* -> channel(HIDDEN);
COMMENTS_EOL_HIDDEN : NEWLINE ->  channel(HIDDEN),popMode;
```

**Comment by ryaneberly** [comment]
The author should have used comments more.... :-)

Looks good, I think.  If all the tests pass, commit it.

**Comment by ryaneberly** [comment]
One of the aims of that logic is to put comments with content into the
HIDDEN channel, but skip blank comments altogether.

**Comment by ryaneberly** [comment]
Nice work.  Thanks Daniel..
