### ISSUE TITLE
Duration codes

### ISSUE THREAD

**Issue by danielgoodwin** [rpgleparser/rpgleparser#26]
Having an issue with parsing of Duration codes for BIFs.
For example

```
     C                   EVAL      HH = %SUBDT(T3: *H)
     C                   EVAL      MN = %SUBDT(T3: *MN)
     C                   EVAL      SC = %SUBDT(T3: *S )
```

It would seems the SPLAT entries are valid at this point , so guessing its something to do with modes.
Does mode need to be pushed and then popped for Duration Codes?

Similar issue with %DIFF. Have added entries in test/bif

**Comment by ryaneberly** [comment]
Hey Daniel.

See line 1112 -  factor2 should be lexing correctly.  The SPLAT_HOURS token is referenced from the DurationCode mode..

I don't know why the durations were kept separate from the whole slew of entities under
// Symbolic Constants  (line 257)

Try moving them out of the DurationCodes mode (which is not used anywhere) into the FREE mode, and see if anything breaks (like lexing multiplication).

Example:
           X = 1*H;
.

**Comment by danielgoodwin** [comment]
Thanks, Ill try that. I believe its not picked up at 1112 as this example is part of an Extended Factor 2, so its is not between 35 and 48.

**Comment by ryaneberly** [comment]
Right.
I meant 1112 shows how it works in fixed.

1112 is not part of free mode.

**Comment by ryaneberly** [comment]
I think the parameters could be a different mode, that would solve some  complexity issues.  Currently the duration codes are giving a bit of grief.

{CALLP{(EMR)}} name( {parm1{:parm2...}} )

What can a parm be?   A literal, a variable, another function or bif or symbolic constant.  Anything else?

Fundamentally, I don't think it can be an expression correct?
Example:
MyProgram( 1 + 2);

**Comment by TheEricWilson** [comment]
If it is a const parm it can be an expression if I remember

**Comment by ryaneberly** [comment]
@TheEricWilson ,  right...   Parameters can be expressions
The issue is currently that *M should lex as a single token in %subdt,  and as 2 tokens pretty much everywhere else.  

Maybe it makes sense to push that part down into the parser.   But, we have almost all of the figurative constants (*BLANK, *ZERO, etc) working correctly in the lexer - I'd rather keep it all there.

**Comment by danielgoodwin** [comment]
Not the same issue.. but Ive added fix for duration code in Result field in a fixed spec.
eg
```
     C     @Date         SubDur    @Monday       @Day#:*D
```

**Comment by ryaneberly** [comment]
Fixed the duration code lexing.  It will only match *M, *S etc if the previous token is a COLON.

@danielgoodwin that fixed subdt, I think adddt will not parse yet.  Do you want to look at that one?
