### ISSUE TITLE
Prototype LIKE with continued identifer

### ISSUE THREAD

**Issue by danielgoodwin** [rpgleparser/rpgleparser#35]
Example where LIKE keyword and field name is a continued identifier

```
     DgetUnitMeasureLongForeignDescription...
     D                 PR                  like(typeUnitMeasureLongDescript ...
     D                                     ion_UTS007)
     DunitMeasure01                        like(typeUnitMeasureCode_UTS007)
     D                                     const
     Dlanguage                             like(typeLanguage) const

```

**Comment by danielgoodwin** [comment]
It would seem that keyword_like with simpleexpression should catch continuedidentifier but does not appear to - dump of symbols shows following

```
DEBUG - 153     KEYWORD_LIKE     @ 43           like
DEBUG - 154     '('      @ 47           (
DEBUG - 155     ID       @ 48           typeUnitMeasureLongDescript
DEBUG - 156     CONTINUATION     @ 75           ...
DEBUG - 157     ID       @ 43           ion_UTS007
DEBUG - 158     ')'      @ 53           )
DEBUG - 159     EOL      @ 99
```
Ive tried a  change based on procedure name continuation but I think I'm missing a mode type scenario

```
keyword_name: PS_CONTINUATION_NAME* PS_NAME;
keyword_expression  : keyword_name |simpleExpression ;

keyword_like : KEYWORD_LIKE OPEN_PAREN name=keyword_expression (COLON like_lengthAdjustment)? CLOSE_PAREN;
```

Like would not be only one in this situ - obviously any of the other LIKE type keywords

**Comment by ryaneberly** [comment]
It seems to work for me.  The result tree looks like this:
 <pre>     (keyword
        (keyword_like
          like
          (
          (simpleExpression
            (identifier
              (free_identifier
                (continuedIdentifier
                  (idOrKeyword typeUnitMeasureLongDescript)
                  ...
                  (idOrKeyword ion_UTS007)
                )
              )
            )
          )
          )
        )
      )</pre>

as opposed to the one w/o a continuation:

<pre>
 (keyword_like
          like
          (
          (simpleExpression
            (identifier (free_identifier (idOrKeyword typeUnitMeasureCode_UTS007)))
          )
          )
        )
</pre>

**Comment by danielgoodwin** [comment]
Sorry about that - took the wrong example, I get an error against line 7 here


```
     D testUnitMeasureShortDescription...
     D                 PR                  extproc('TESTUNITMEASURESHORTDESCRIP-
     D                                     TION_UTS007')
     D                                     like(typeMessageID)
     D  unitMeasureShortDescription...
     D                                     like(typeUnitMeasureShortDescript...
     D                                     ion_UTS007) const
     D
     D  unitMeasureCode...
     D                                     like(typeUnitMeasureCode_UTS007)
     D                                     options(*nopass)
     D  unitMeasureLongDescription...
     D                                     like(typeUnitMeasureLongDescript...
     D                                     ion_UTS007)
     D                                     options(*nopass)
```

**Comment by ryaneberly** [comment]
fixed.  thanks Daniel.
