### ISSUE TITLE
Tree walking with IF directives

### ISSUE THREAD

**Issue by danielgoodwin** [rpgleparser/rpgleparser#38]
I have an example, which parses ok, but when I go to walk the tree? to produce output, I get an error message. 

```
line 6:23 no viable alternative at input 'DP@AcgCde    '
```

```
      /If Not Defined( Copy_Procedure_Interface )
     D RtvAcgCde       PR                  ExtPgm('RTVACGCDE')
      /Else
     D RtvAcgCde       PI
      /EndIf
     D  P@AcgCde                     15A
     D  P@LocType                     1A
```

**Comment by ryaneberly** [comment]
The scope of getting this to work was significant....  it seems there is no standard recipe for precompile directives in the antlr world.   At there is no way to handle this in the parser.

I added a TokenSource that wraps the Lexer TokenSource.  It hides the IF,DEFINE, and UNDEFINE directives, and implements the effects in the same fashion the compiler would.   We could implement /COPY and /INCLUDE in this as well.   

See the use of _PreprocessTokenSource_ in TestFiles:67-68

```
	final RpgLexer rpglexer = new RpgLexer(input);
        final TokenSource lexer = new PreprocessTokenSource(rpglexer);
        final CommonTokenStream tokens = new CommonTokenStream(lexer);
```

See examples of it being parsed in:
resources\org\rpgleparser\tests\directives\ IF_directive_38.expected.txt
resources\org\rpgleparser\tests\directives\ IF_directive_38b.expected.txt
