### ISSUE TITLE
DS statement without FROM/TO POSITIONS does not work

### ISSUE THREAD

**Issue by UdayaBhanuG** [rpgleparser/rpgleparser#39]
The below valid syntax does not parse. 

      **********************************************************************
     d wwdata          ds
     d  wwpcom                 1      4
     d  wwrest                 5    256
      *

It fails saying the following:

line 838:25 mismatched input '\r\n' expecting FROM_POSITION

I guess FROM/TO_POSITION etc... should not be made mandatory.

**Comment by ryaneberly** [comment]
Hi,
  I added the example you mentioned to the tests, and it appears to parse fine.
https://github.com/rpgleparser/rpgleparser/commit/7d989383976b5fc31352b0b384b7369822813fc0

  Could you provide a bit more detail on how to reproduce the problem?

   Are you using FixedWidthBufferedReader?  That ensures each line is at least 80 characters.

  See org.rpgleparser.integration.TestFiles.test() for a full example on using the parser (including 2 stage parsing)

**Comment by UdayaBhanuG** [comment]
Once I started using FixedWidthBufferedReader, the error disappeared. Thanks.
