### ISSUE TITLE
When using the generated base listener many tokens are terminal nodes rather than typed

### ISSUE THREAD

**Issue by TheEricWilson** [rpgleparser/rpgleparser#4]
My intended use of this is to use the listener and get the "parts of speech" labeling for each token rather than doing it by token position. For example it is essential to be able to know the result indicators whether be in the Hi or Lo or Eq positions. What is in Factor1, Factor 2, and Result.... What is the opcode...

Right now as things are being parsed I would have to do a lot of error prone coding to decide which ordinal position in the token stream is what. 

I have made a modification to my POM to create a jar which I reference in a separate project for the Listener stuff.

**Comment by ryaneberly** [comment]
I agree.  I'll take a shot at it.

The key is to 'name' the tokens.

cspec_fixed: C_SPEC_FIXED
(C_CONTROL_LEVEL | C_CONTROL_LEVEL_COND )
C_INDICATORS C_FACTOR
(cspec_fixed_standard|cspec_fixed_x2);

should become something like:


cspec_fixed: C_SPEC_FIXED
(C_CONTROL_LEVEL | C_CONTROL_LEVEL_COND )
hi=C_INDICATOR
lo=C_INDICATOR
eq=C_INDICATOR C_FACTOR
(cspec_fixed_standard|cspec_fixed_x2);

then the hi,lo,eq fields are available on the context.

**Comment by ryaneberly** [comment]
Eric,
   Give the updated C-spec a try.

**Comment by TheEricWilson** [comment]
Running TestFixed C an telling it to show the parse tree I am getting the following

line 1:25 token recognition error at: 'KLIST'
line 1:30 no viable alternative at input '<EOF>'
[@0,5:5='C',<9>,1:5] - C_SPEC_FIXED
[@1,6:7='  ',<242>,1:6] - C_CONTROL_LEVEL
[@2,8:10='   ',<244>,1:8] - C_INDICATORS
[@3,11:24='WCKEY1        ',<245>,1:11] - C_FACTOR
(r (cspec_fixed C        WCKEY1        ))

**Comment by ryaneberly** [comment]
Hmm. good point...
expectTokensForSourceLines() auto pads the line out to the full source line width.
TestUtils.showParseTree(inputString) - does not.

try:
TestUtils.showParseTree(TestUtils.padSourceLines(inputString,false));

I have mixed feelings about this.  I don't think we need to make the parser capable of handling mixed length lines.  Maybe we should harden showParseTree() to at least give a warning.

David, thoughts?

**Comment by TheEricWilson** [comment]
Ok padding out the string I end up getting it running down the Free format path :-(
I am just learning ANTLR right now, but if we get things working with the C-Specs I should be able to replicate the pattern for the others.

line 1:19 no viable alternative at input 'CWCKEY1'
[@-1,-1:-1='<missing FREE_SEMI>',<156>,1:13] - FREE_SEMI
[@0,13:13='C',<142>,1:13] - FREE_ID
[@-1,-1:-1='<missing FREE_SEMI>',<156>,1:19] - FREE_SEMI
[@1,19:24='WCKEY1',<142>,1:19] - FREE_ID
[@-1,-1:-1='<missing FREE_SEMI>',<156>,1:33] - FREE_SEMI
[@2,33:37='KLIST',<142>,1:33] - FREE_ID
[@-1,-1:-1='<missing FREE_SEMI>',<156>,1:33] - FREE_SEMI
(r (free (baseExpression (expression identifier)) <missing FREE_SEMI>) (free (baseExpression (expression (identifier C))) <missing FREE_SEMI>) (free (baseExpression (expression (identifier WCKEY1))) <missing FREE_SEMI>) (free (baseExpression (expression (identifier KLIST))) <missing FREE_SEMI>))

**Comment by ryaneberly** [comment]
Mm.. did the position of the 'C' move on you?
With this:
    @Test
    public void testKLIST() {
        String inputString = "     C     WCKEY1        KLIST";
        //expectTokensForSourceLines(inputString, "C", "", "", "WCKEY1", "KLIST", "", "", "", "", "", "", "", "");
        TestUtils.showParseTree(TestUtils.padSourceLines(inputString,false));
    }

I get this:
![image](https://cloud.githubusercontent.com/assets/5986747/6711736/2f7c164e-cd5f-11e4-9b18-8b9300f1c1b0.png)

**Comment by TheEricWilson** [comment]
I bet the code for the pad was taken from the one that was written for free form (inserts spaces in the front as well as the back.) There was a pad function for fixed that only appended spaces.

**Comment by TheEricWilson** [comment]
Yep the code to pad adds beginning spaces if you specify snippet=true… Switched to false and it was better :-)

Still I would expect that the klist would be identified as the op-code and the wckey1 would be identified as factor1...

**Comment by TheEricWilson** [comment]
[@0,5:5='C',<9>,1:5] - C_SPEC_FIXED
[@1,6:7='  ',<242>,1:6] - C_CONTROL_LEVEL
[@2,8:10='   ',<244>,1:8] - C_INDICATORS
[@3,11:24='WCKEY1        ',<245>,1:11] - C_FACTOR
Interesting that the things show up in the token list but not in the tree view... 

[@4,25:34='KLIST     ',<247>,1:25] - C_OP_AND_EXTNDR
[@5,35:48='              ',<245>,1:35] - C_FACTOR
[@6,49:62='              ',<245>,1:49] - C_FACTOR
[@7,63:67='     ',<248>,1:63] - C_FIELD_LENGTH
[@8,68:69='  ',<249>,1:68] - C_DECIMAL_POSITIONS
[@9,70:75='      ',<250>,1:70] - C_RESULTING_INDICATORS
[@10,112:113='\r\n',<253>,1:112] - C_EOL
(r (cspec_fixed C        WCKEY1         (cspec_fixed_standard KLIST                                                    rn
)))

**Comment by ryaneberly** [comment]
The GUI tree doesn't show you the "name" of the tokens.
If you look at the cspec_fixed_standard context class you'll see it has a
hi,lo, and eq field.

But I don't see harm in building that out 1 level.

Change:
cspec_fixed_standard: operation=C_OP_AND_EXTNDR
factor2=C_FACTOR
result=C_FACTOR
len=C_FIELD_LENGTH
decimalPositions=C_DECIMAL_POSITIONS
hi=C_RESULTING_INDICATOR
lo=C_RESULTING_INDICATOR
eq=C_RESULTING_INDICATOR
cspec_fixed_comments? C_EOL;

to something like:
cspec_fixed_standard: operation=C_OP_AND_EXTNDR
factor2=C_FACTOR
result=C_FACTOR
len=C_FIELD_LENGTH
decimalPositions=C_DECIMAL_POSITIONS
hi=hiIndicator
lo=loIndicator
eq=eqIndicator
cspec_fixed_comments? C_EOL;

hiIndicator:
C_RESULTING_INDICATOR
;
loIndicator:
C_RESULTING_INDICATOR
;
eqIndicator:
C_RESULTING_INDICATOR
;

then you will get a additional listener method for each indicator.
And the cspec_fixed_standard context object will have
ctx.hiIndicator(), ctx.loIndicator(), ctx.eqIndicator()  methods in it.
And you will see them in the tree gui.

as well as what it has under the existing code
ctx.hi, ctx.lo, ctx.eq

Have fun :-)

**Comment by DavidGregory084** [comment]
Hi all, sorry for being late to the party; I kind of neglected `showParseTree` because it's not used in any of the tests - it probably should be able to accept some indication of the context of the input like you say!
You're absolutely right: I collapsed `pad280` and `pad280Free` into `padSourceLines` and then hid usages inside the `expect...` assertion methods - maybe I should change the second parameter to `isFreeSnippet` rather than `isSnippet` as this should make it a little clearer to use.
You can get access to the token names as in the snippet below:

```java
ANTLRInputStream input = new ANTLRInputStream(inputString);
RpgLexer lexer = new RpgLexer(input);
Vocabulary vocabulary = lexer.getVocabulary();
CommonToken token; // A token from a ParseTree object
String displayName = vocabulary.getDisplayName(token.getType())
```

**Comment by ryaneberly** [comment]
Thanks,
  I added TestUtils.printTokens(List<Token> tokens).
and TestUtils.printTokens(String inputString, Boolean isFreeSnippet)

**Comment by TheEricWilson** [comment]
Things are looking pretty good so far, I am going to mark this closed.
