### ISSUE TITLE
Fixed c-spec comments in column 77+

### ISSUE THREAD

**Issue by danielgoodwin** [rpgleparser/rpgleparser#44]
Seems undocumented, but appears ILE compiler/SEU is ok with comments on some fixed line specs, specifically, this seems to include the ENDXX ops at least from col 77+

```
     C*
     C                   ENDSL                                              Subf 
```

**Comment by ryaneberly** [comment]
Interesting.  We'll need to look into this further.

**Comment by DavidGregory084** [comment]
The details of this are documented in the [RPG Reference](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_72/rzasd/calss.htm):
```
Figure 1. Calculation Specification Layout
*.. 1 ...+... 2 ...+... 3 ...+... 4 ...+... 5 ...+... 6 ...+... 7 ...+... 8 ...+... 9 ...+... 10
CL0N01Factor1+++++++Opcode(E)+Factor2+++++++Result++++++++Len++D+HiLoEq....Comments++++++++++++
CL0N01Factor1+++++++Opcode(E)+Extended-factor2+++++++++++++++++++++++++++++Comments++++++++++++
```

**Comment by danielgoodwin** [comment]
OK, so in cases of Fixed specs that do not have extended factor2, we can 'ignore' from column 77
Ive added a change to parser for this, and a test case.

```
cs_fixed_comments:CS_FixedComments;		
...

CS_Comments : ~[\r\n] {getCharPositionInLine()>80}? ~[\r\n]*  ; // skip spaces, tabs, newlines
CS_FixedComments : ~[\r\n] {getCharPositionInLine()>=77}? ~[\r\n]*  ; // skip spaces, tabs, newlines
```

**Comment by ryaneberly** [comment]
That's great. thanks
