### ISSUE TITLE
Implement 2 stage parsing?

### ISSUE THREAD

**Issue by ryaneberly** [rpgleparser/rpgleparser#5]
The Antlr authors recommend it

https://theantlrguy.atlassian.net/wiki/pages/viewpage.action?pageId=1900591

**Comment by DavidGregory084** [comment]
Possibly premature optimisation for now?

**Comment by ryaneberly** [comment]
Now that is a great point.  I'm open to waiting.  I really haven't seen any
evidence of performance issues with our project here..

I ran into some real issues on another parsing project, that 2 stage
resolved.

The antlr 4 author (T Parr) suggests it, and the 2nd main contributor (S
Harwell) says he "always" uses it.
https://github.com/antlr/antlr4/issues/192


It is also a 10 liner....
However, won't take this further without a consensus :-).

**Comment by ryaneberly** [comment]
closing.  not at this point.
