### ISSUE TITLE
error(50) Syntax Error : '->' came as a complete surprise to me while matching a lexer rule

### ISSUE THREAD

**Issue by dhawkinstx** [rpgleparser/rpgleparser#50]
First of all, please forgive me as I'm new to antlr, 
I'm trying to get your rpgleparser working with in .net.  Both ANTLRWorks 2.1 and Visual Studio's ANTLR4 build choke on the RpgLexer.g4 lexer file on lines like:

`OP_NoSpace: -> skip,mode(FREE);//,pushMode(FreeOpExtender);`
`NumberContinuation_ANY: -> popMode,skip;`
`EatCommentLinesPlus_Any: -> popMode,skip;`
`EatCommentLines_NothingLeft: -> popMode,skip;`
etc...

Any idea why it doesn't like the syntax or what I can do to get it working?

Thanks,
--David

**Comment by dhawkinstx** [comment]
I was able to resolve the problem. It's related to antlr4's support for zero-length tokens.  The workaround is described here: [Empty zero-length tokens cannot have lexer commands #687](https://github.com/antlr/antlr4/issues/687)

The fix is to specify the rules like:
```
OP_NoSpace
    :   {}// intentionally empty
        -> skip,mode(FREE)
    ;
```

Thanks,
--David

**Comment by ryaneberly** [comment]
Let's open this to make the changes if it makes sense.   A pull request is welcome :)

**Comment by DavidGregory084** [comment]
@dhawkinstx -  from the issue linked above (antlr/antlr4#687) it looks like this was fixed in antlr/antlr4#691 which was in the ANTLR 4.5 milestone. Are you able to upgrade or are there no released versions of those tools using ANTLR 4.5 yet?

**Comment by ryaneberly** [comment]
Ah, I misunderstood that a code change to the rpg lexer was in order.

We use antlr 4.5.3 in the maven build,  I'm not sure what level the tools are at.

**Comment by DavidGregory084** [comment]
Sorry Ryan, my previous comment wasn't very clear!
@dhawkinstx has tried using ANTLRWorks 2.1 and Visual Studio's ANTLR4 plugin and it looks like those tools are built against an old version of ANTLR which doesn't have a fix for this and therefore can't interpret rpgleparser's grammars correctly.
I don't think there is necessarily any change required at this end - although if @dhawkinstx wants to open a PR implementing the empty brace fix above for compatibility with older versions of ANTLR I don't think that would cause any trouble for other users?

**Comment by ryaneberly** [comment]
Agreed,  No problem David, appreciate the input.
