### ISSUE TITLE
/IF DEFINED directive inside of a SELECT statement not handled

### ISSUE THREAD

**Issue by dhawkinstx** [rpgleparser/rpgleparser#51]
It doesn't appear that the parser is currently handling the case when an /IF DEFINED directive is placed within a SELECT.  Once again, I am new to ANTLR and this one isn't obvious to me how to fix properly.
I've provided a sample file illustrating the problem.

[IFSELECT.TXT](https://github.com/rpgleparser/rpgleparser/files/322297/IFSELECT.TXT)

line 2:5 mismatched input ' /' expecting {CS_FIXED, OP_ENDSL, OP_OTHER, OP_WHEN}
line 3:25 no viable alternative at input 'C                   WHEN'

Thanks,
--David

**Comment by dhawkinstx** [comment]
Errr. Scratch that.  I now understand that I need to push everything through the PreprocessTokenSource before parsing.  It is what takes care of handling the defines.  It has no problem parsing the content once I use it.

Thanks
--David

**Comment by dhawkinstx** [comment]
Closing due to this not being a problem as long as you use the PreprocessTokenSource.

**Comment by ryaneberly** [comment]
You got it!
