### ISSUE TITLE
Exponentiation operator (**) does not get parsed properly.

### ISSUE THREAD

**Issue by UdayaBhanuG** [rpgleparser/rpgleparser#57]
** in a source member does not get parsed properly. It confuses that with ID, which is defined as follows:

ID : ('\*' {getCharPositionInLine()>7}? '\*'? [a-zA-Z])?
        [#@%$a-zA-Z]{getCharPositionInLine()>7}? [#@$a-zA-Z0-9_]* ;

Two consecutive stars possibility in ID definition is what is confusing it. If I remove the second * (*? one), it parses fine, but dont know which other issues it might cause. Please fix the issue.

**Comment by ryaneberly** [comment]
example:
FVAnn = PerPayment * (((1+i)**n -1)/i);

**Comment by ryaneberly** [comment]
@UdayaBhanuG , Could you provide a source example.
This test works:
/rpgleparser/src/test/resources/org/rpgleparser/tests/nesting/procedure/procedure2.rpgle
