### ISSUE TITLE
leading underscore in identifiers/procedure names

### ISSUE THREAD

**Issue by TorstenKlinge** [rpgleparser/rpgleparser#62]
The following code raises an exception

`     C                   EVAL      goASWFileForORSHE = ASWJob...      `                     
`     C                             _getFileByName('SROORSHE')                 `

line 4:35 token recognition error at: '_getF'

The problem seem to be the underscore at the beginning of getFileName

The problem appears in 

`     C                   EVAL      goASWFileForORSHE = _getFileByName('SROORSHE')                 `

as well

**Comment by ryaneberly** [comment]
@TorstenKlinge .   Thanks, this is fixed.
