### ISSUE TITLE
dir_include doesn't support the comments and generates the error

### ISSUE THREAD

**Issue by kishore74lko** [rpgleparser/rpgleparser#65]
**dir_include** doesn't support the comments and generates the error:

```
dir_include: (DIR_INCLUDE 

            (
			
              (((library=copyText DIR_Slash)? file=copyText)? member=copyText)
			  
              | (DIR_Slash? (copyText DIR_Slash)+ copyText)
			  
            ) 
			
             );
```
If the source line is
`/include QCPYSRC,FLDATTRS                   Field Attributes`
Then the generated error is
`line 2:52 mismatched input 'Field' expecting {<EOF>, EOL}`

**Comment by ryaneberly** [comment]
Thanks @kishore74lko.   I'll try to look at fixing this soon.   You've obviously been able to make some use of  parser.   I'm curious, what is your use case if you don't mind sharing?

**Comment by ryaneberly** [comment]
fixed in dev branch

**Comment by kishore74lko** [comment]
Thanks @ ryaneberly, for a quick fix and reply.

FYI: I am new learner of fully free RPGLE, and some idea of Antlr parsing, so trying to parser some information by **rpgleparser**.

**Comment by kishore74lko** [comment]
@ryaneberly, Another parsing error found on same type case of **INCLUDE** directive having comments
 
`/include QDDSSRC,QUSROBJK                   Retrieve Object Description (QUSROBJD) API`

And the errors are: 

`line 46:80 extraneous input '(' expecting {<EOF>, DIR_OtherText, EOL}`

So, it seems that comments could be any character except [\r\n], which is not handled by the lexer rule:
`DIR_OtherText : ~[/'"\r\n \t,()]+ ;`
