### ISSUE TITLE
maven central version - 1.0.0 - versus pom.xml version - 0.2-SNAPSHOT -: inconsistency

### ISSUE THREAD

**Issue by zosrothko** [rpgleparser/rpgleparser#76]
Hi

The README explains that 
```
RPGLEParser is on now on maven:

    <dependency>
        <groupId>com.github.rpgleparser</groupId>
        <artifactId>rpgleparser</artifactId>
        <version>1.0.0</version>
    </dependency>
```
while le pom.xml version @master branch is `<version>0.2-SNAPSHOT</version>`

How could it be?

**Comment by lipka-clazzpl** [comment]
Hi @zosrothko, if You would like to tinker with parser, please fork from `dev` branch from which release was done  (which is 35 commits ahead of master).

If You look carefully, package is named differently in `master`s `pom.xml`.

**Comment by zosrothko** [comment]
Since the artifact on Maven central is the 1.0.0, please make the dev branch as the default! Thx

**Comment by ryaneberly** [comment]
dev is default.  Thanks for the hint - I didn't know about the default branch setting

**Comment by zosrothko** [comment]
fine. By the way, the classic naming convention when using git is to have

1. A master branch: the reference
2. A release branch: latest released version
3. Optional feature branches: WIP

I would suggest 

1. to rename your 'dev' branch intot 'release' since it has been pushed on Maven central
2. to change its version to: `1.0.1-SNAPSHOT` or whatever SNAPSHOT version
3. to use `<tag>HEAD</tag>` in the `<scm>` element
so that you could use the `mvn release` process to publish a new version.
