### ISSUE TITLE
Unit tests are failing: [ERROR] Tests run: 400, Failures: 258, Errors: 0, Skipped: 1

### ISSUE THREAD

**Issue by zosrothko** [rpgleparser/rpgleparser#77]
Hi

Building the dev branch produces a lot of unit test failure. Moreover, there are some FileNotFoundException like
`java.io.FileNotFoundException: src\test\resources\org\rpgleparser\tests\directives\copy.rpgle\MBR1.copy`.
Could you fix those failures so that fixes can be added with a secure base code?
Thanks

Here the `mvn clean install -l mvn.log` [mvn.log](https://github.com/rpgleparser/rpgleparser/files/5779678/mvn.log)

```
C:\Users\fandre\Documents\MXW\RPG\rpgleparser>git show
commit 8da6287a941c1ebd88f867348cb26c441e6fb79e (HEAD -> dev, rpgleparser/dev, origin/dev)
Merge: b980f75 7333428
Author: Ryan Eberly <ryan.eberly@goodville.com>
Date:   Fri Mar 1 21:20:31 2019 -0500

    Merge branch 'master' into dev

```

**Comment by ryaneberly** [comment]
Fixed a few tests on #79

maven clean install 
works for me on dev.

Closing.  Reopen if you still have issues (on Windows)
