### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by nmusatti** [rpgleparser/rpgleparser#82]
I noticed that rpgleparser has been getting about one commit every six months for the last few years. Is there any maintainer still active? I'd volunteer, as I need to use it for a project at work, but I really don't know RPG, so I'm not sure I'd be of any use to others. On the other hand I'd rather resume maintenance of the original project, rather than forking it.

**Comment by ryaneberly** [comment]
Thanks for asking @nmusatti , I've added you as a maintainer.   I haven't been giving this project much attention, though it's exciting to see it in use!
