### ISSUE TITLE
Literal blank problem 

### ISSUE THREAD

**Issue by ryaneberly** [rpgleparser/rpgleparser#9]
I found that literals other than blanks are ok as well as figurative constants. I left the tests showing the parse tree so the evidence would be easy to see -Eric

**Comment by ryaneberly** [comment]
Thanks Eric.  it's a bit ugly, but try now.

**Comment by TheEricWilson** [comment]
Hmmm the test

testMove in TestCFactors  is still failing (each quote mark is being recognized as a token by themselves and throwing everything off…

**Comment by ryaneberly** [comment]
oops missed that.  The tokens between the quotes excluded whitespace.  tco.

**Comment by TheEricWilson** [comment]
Thanks man! Everything seems to be working once again

**Comment by ryaneberly** [comment]
My pleasure.  I appreciate you finding the problem while the change was
still fresh in memory.
